# Generated by Django 4.2.30 on 2026-10-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('PPT', 'Permiso por protección temporal'), ('MS', 'Menor sin identificación'), ('AS', 'Adulto sin identificación')], max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('indeterminado', 'Indeterminado')], max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='pacientes.eps', verbose_name='EPS')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='paciente_documento_unico'),
        ),
    ]
