# Generated by Django 4.2.29 on 2026-03-14 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('campos_requeridos', models.JSONField(default=list, help_text='Lista JSON de los campos requeridos para esta patología.', verbose_name='Campos requeridos')),
                ('protocolo_medico', models.TextField(blank=True, help_text='Protocolo médico asociado a esta patología.', verbose_name='Protocolo médico')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patología',
                'verbose_name_plural': 'Patologías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caso', models.CharField(max_length=50, unique=True, verbose_name='Número de caso')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('tipo_muestra', models.CharField(blank=True, max_length=200, verbose_name='Tipo de muestra')),
                ('datos_ingresados', models.JSONField(default=dict, help_text='JSON con los valores del formulario dinámico.', verbose_name='Datos ingresados')),
                ('texto_generado', models.TextField(blank=True, help_text='Descripción macroscópica generada automáticamente.', verbose_name='Texto generado')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('patologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='informes.patologia', verbose_name='Patología')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_nombre', models.CharField(max_length=150, verbose_name='Nombre del campo')),
                ('campo_label', models.CharField(blank=True, max_length=200, verbose_name='Etiqueta visible')),
                ('tipo_campo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('lista', 'Lista desplegable'), ('textarea', 'Área de texto'), ('boolean', 'Sí / No')], default='texto', max_length=20, verbose_name='Tipo de campo')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Lista de opciones para campos de tipo lista.', verbose_name='Opciones')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('valor_defecto', models.CharField(blank=True, max_length=255, verbose_name='Valor por defecto')),
                ('patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='informes.patologia', verbose_name='Patología')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['patologia', 'orden'],
                'unique_together': {('patologia', 'campo_nombre')},
            },
        ),
    ]
