# Generated by Django 4.2.30 on 2026-10-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_categoria_patologia_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patologia',
            name='campos_requeridos',
        ),
    ]
