# Generated by Django 4.2.30 on 2026-10-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente'),
        ('informes', '0007_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='pacientes.eps', verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='informe',
            name='estudios_solicitados',
            field=models.TextField(blank=True, verbose_name='Estudios solicitados'),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='informe',
            name='medico_tratante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Médico tratante'),
        ),
        migrations.AddField(
            model_name='informe',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='informe',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='informes.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='informe',
            name='tipo_estudio',
            field=models.CharField(choices=[('histologia', 'Histología'), ('citologia_no_ginecologica', 'Citología no ginecológica'), ('citologia_cervicovaginal', 'Citología cérvico-vaginal'), ('inmunohistoquimica', 'Inmunohistoquímica'), ('intraoperatorio', 'Estudio intraoperatorio por congelación'), ('revision_laminas', 'Revisión de láminas (segunda opinión)')], default='histologia', max_length=30, verbose_name='Tipo de estudio'),
        ),
    ]
