# Generated by Django 4.2.30 on 2026-10-05 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informes', '0010_finalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('motivo', models.CharField(max_length=300, verbose_name='Motivo')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('firma', models.JSONField(verbose_name='Firma')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adendas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adendas', to='informes.informe', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Adenda',
                'verbose_name_plural': 'Adendas',
                'ordering': ['informe', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='adenda',
            constraint=models.UniqueConstraint(fields=('informe', 'numero'), name='adenda_numero_unico'),
        ),
    ]
